### ISSUE TITLE
Fix busted score to database

### ISSUE THREAD

**Issue by bryandijkhuizen** [bryandijkhuizen/dartproject-s7#35]
Busted scores (dead throws) are added to the database as a score. If the score is dead, the score should be 0

**Comment by Ranthyr** [comment]
Gevonden door: Bryan Dijkhuizen
Omschrijving:
Dead throws worden in de databse ingevoerd met de gegooide score, deze score zou 0 moeten zijn.

Stappen om te reproduceren:
1. Start een match.
2. Vul scores in totdat er dead throws gegooid kunnen worden.
3. Gooi een  dead throw.

Waar zit het probleem:
Het probleem zit in de match store, hier worden scores ingevoerd in de database en bij dead throws wordt meegegeven of het een dead throw is of niet maar wordt ook de score meegestuurd.

Prioriteit: Gemiddeld

Risico's: Geen veiligheidsrisico's, maar dit probleem zorgt wel voor inaccurate statistieken.

Tijd die het kost om op te lossen: 30 minuten.

**Comment by Ranthyr** [comment]
Issue opgelost door Jelmer, dead throws worden nu ingevuld als 0 in de database.
